import { Injectable } from '@angular/core';
import { delay, map, Observable, of } from 'rxjs';

export type Contact = {
  id: string;
  age: number;
  name: string;
  gender: string;
  email: string;
  company: string;
}

@Injectable()
export class ContactsClientService {
  private contacts: Contact[] = [
    {
      "id": "5b2eee0a8fdd5b71c8148490",
      "age": 29,
      "name": "Campos York",
      "gender": "male",
      "company": "AVENETRO",
      "email": "camposyork@avenetro.com",
    },
    {
      "id": "5b2eee0a9cd29e820c10edad",
      "age": 20,
      "name": "Esperanza Boone",
      "gender": "female",
      "company": "COSMETEX",
      "email": "esperanzaboone@cosmetex.com",
    },
    {
      "id": "5b2eee0a582ba867abbd7ce7",
      "age": 39,
      "name": "Holden Barry",
      "gender": "male",
      "company": "CODAX",
      "email": "holdenbarry@codax.com",
    },
    {
      "id": "5b2eee0afe5f471c63fa7acf",
      "age": 22,
      "name": "Daniels Barlow",
      "gender": "male",
      "company": "OPTICOM",
      "email": "danielsbarlow@opticom.com",
    },
    {
      "id": "5b2eee0af534aab9ece2f890",
      "age": 23,
      "name": "Leigh Burris",
      "gender": "female",
      "company": "KINETICUT",
      "email": "leighburris@kineticut.com",
    },
    {
      "id": "5b2eee0ac42f319d1c980d93",
      "age": 35,
      "name": "Floyd Little",
      "gender": "male",
      "company": "FURNAFIX",
      "email": "floydlittle@furnafix.com",
    },
    {
      "id": "5b2eee0a20b705a9c1d4b8c9",
      "age": 28,
      "name": "Josie Henson",
      "gender": "female",
      "company": "MICROLUXE",
      "email": "josiehenson@microluxe.com",
    },
    {
      "id": "5b2eee0a6fb14c569982fa9d",
      "age": 37,
      "name": "Carrillo Harmon",
      "gender": "male",
      "company": "PHOTOBIN",
      "email": "carrilloharmon@photobin.com",
    },
    {
      "id": "5b2eee0a956cbb97ebf666c7",
      "age": 20,
      "name": "Wilkerson Zamora",
      "gender": "male",
      "company": "EVEREST",
      "email": "wilkersonzamora@everest.com",
    },
    {
      "id": "5b2eee0a8c166f1515f51513",
      "age": 27,
      "name": "Robles Romero",
      "gender": "male",
      "company": "MAKINGWAY",
      "email": "roblesromero@makingway.com",
    },
    {
      "id": "5b2eee0a7f5b9af99637f6e0",
      "age": 40,
      "name": "Staci Hudson",
      "gender": "female",
      "company": "EXOPLODE",
      "email": "stacihudson@exoplode.com",
    },
    {
      "id": "5b2eee0a323805f237217ef3",
      "age": 22,
      "name": "Benjamin Casey",
      "gender": "male",
      "company": "HARMONEY",
      "email": "benjamincasey@harmoney.com",
    },
    {
      "id": "5b2eee0a1066bbb9d00b729d",
      "age": 23,
      "name": "Green Ochoa",
      "gender": "male",
      "company": "MEDCOM",
      "email": "greenochoa@medcom.com",
    },
    {
      "id": "5b2eee0a991a448593d9e9b9",
      "age": 25,
      "name": "Noreen Bradley",
      "gender": "female",
      "company": "MIXERS",
      "email": "noreenbradley@mixers.com",
    },
    {
      "id": "5b2eee0aa986bb818b67983c",
      "age": 30,
      "name": "Ellis Lynch",
      "gender": "male",
      "company": "GLEAMINK",
      "email": "ellislynch@gleamink.com",
    },
    {
      "id": "5b2eee0a45146bd6c166ffdb",
      "age": 40,
      "name": "Mara Patrick",
      "gender": "female",
      "company": "DIGIGEN",
      "email": "marapatrick@digigen.com",
    },
    {
      "id": "5b2eee0a06886543e3a17aa8",
      "age": 35,
      "name": "Ashley Torres",
      "gender": "male",
      "company": "QNEKT",
      "email": "ashleytorres@qnekt.com",
    },
    {
      "id": "5b2eee0a042b6d2148655f33",
      "age": 39,
      "name": "Fields Johnson",
      "gender": "male",
      "company": "MEDMEX",
      "email": "fieldsjohnson@medmex.com",
    },
    {
      "id": "5b2eee0a2485240da72097e2",
      "age": 21,
      "name": "Rose Greene",
      "gender": "male",
      "company": "MANTRO",
      "email": "rosegreene@mantro.com",
    },
    {
      "id": "5b2eee0a23ae081ae8f048c9",
      "age": 39,
      "name": "Diana Jefferson",
      "gender": "female",
      "company": "ISOLOGICA",
      "email": "dianajefferson@isologica.com",
    },
    {
      "id": "5b2eee0a14274e100c4bc499",
      "age": 28,
      "name": "Davis Grimes",
      "gender": "male",
      "company": "TECHADE",
      "email": "davisgrimes@techade.com",
    },
    {
      "id": "5b2eee0ac30a6e87ef0ad66c",
      "age": 30,
      "name": "Margo Huffman",
      "gender": "female",
      "company": "ORBEAN",
      "email": "margohuffman@orbean.com",
    },
    {
      "id": "5b2eee0abe82e8acbee64a1c",
      "age": 25,
      "name": "Hooper Sanchez",
      "gender": "male",
      "company": "CEDWARD",
      "email": "hoopersanchez@cedward.com",
    },
    {
      "id": "5b2eee0a3403d850804cda03",
      "age": 30,
      "name": "Beard Hall",
      "gender": "male",
      "company": "TRANSLINK",
      "email": "beardhall@translink.com",
    },
    {
      "id": "5b2eee0a50f2c44111e2c56b",
      "age": 37,
      "name": "Mcmillan Rich",
      "gender": "male",
      "company": "SULTRAX",
      "email": "mcmillanrich@sultrax.com",
    },
    {
      "id": "5b2eee0a2eab50bb8894b87d",
      "age": 23,
      "name": "Nixon Garrett",
      "gender": "male",
      "company": "GYNKO",
      "email": "nixongarrett@gynko.com",
    },
    {
      "id": "5b2eee0a1e1af1fce24adf05",
      "age": 34,
      "name": "Wilkins Rogers",
      "gender": "male",
      "company": "XSPORTS",
      "email": "wilkinsrogers@xsports.com",
    },
    {
      "id": "5b2eee0a9c1e79971cc9a977",
      "age": 36,
      "name": "Evelyn Weeks",
      "gender": "female",
      "company": "SEALOUD",
      "email": "evelynweeks@sealoud.com",
    },
    {
      "id": "5b2eee0a8a3caf155063f806",
      "age": 30,
      "name": "Holcomb Pope",
      "gender": "male",
      "company": "GLASSTEP",
      "email": "holcombpope@glasstep.com",
    },
    {
      "id": "5b2eee0a6248fdf28c977861",
      "age": 33,
      "name": "Robert Gilbert",
      "gender": "female",
      "company": "SECURIA",
      "email": "robertgilbert@securia.com",
    },
    {
      "id": "5b2eee0a5d74174f81a150d5",
      "age": 22,
      "name": "Katie Newton",
      "gender": "female",
      "company": "ENDIPIN",
      "email": "katienewton@endipin.com",
    },
    {
      "id": "5b2eee0ae995fb6017906ba8",
      "age": 29,
      "name": "Carmen Rosario",
      "gender": "female",
      "company": "DOGTOWN",
      "email": "carmenrosario@dogtown.com",
    },
    {
      "id": "5b2eee0aa23b6a64fb547bf0",
      "age": 20,
      "name": "Chaney Swanson",
      "gender": "male",
      "company": "MEGALL",
      "email": "chaneyswanson@megall.com",
    },
    {
      "id": "5b2eee0ac61ac2f049344827",
      "age": 29,
      "name": "Pate Wise",
      "gender": "male",
      "company": "DRAGBOT",
      "email": "patewise@dragbot.com",
    },
    {
      "id": "5b2eee0a47fb8ce5d2d57ac2",
      "age": 23,
      "name": "Vaughn Bernard",
      "gender": "male",
      "company": "PRISMATIC",
      "email": "vaughnbernard@prismatic.com",
    },
    {
      "id": "5b2eee0a8dd0a7a7887a08e2",
      "age": 21,
      "name": "Cassie Dyer",
      "gender": "female",
      "company": "ISOLOGIX",
      "email": "cassiedyer@isologix.com",
    },
    {
      "id": "5b2eee0a78b348b0a4af2b62",
      "age": 28,
      "name": "Rush Bryant",
      "gender": "male",
      "company": "ZERBINA",
      "email": "rushbryant@zerbina.com",
    },
    {
      "id": "5b2eee0a5f5a6e12f55bb90f",
      "age": 24,
      "name": "Jocelyn Workman",
      "gender": "female",
      "company": "ATOMICA",
      "email": "jocelynworkman@atomica.com",
    },
    {
      "id": "5b2eee0acb32bc4d18769d5f",
      "age": 23,
      "name": "Pam Edwards",
      "gender": "female",
      "company": "QUANTALIA",
      "email": "pamedwards@quantalia.com",
    },
    {
      "id": "5b2eee0a3415794a87a7caf8",
      "age": 36,
      "name": "White Brady",
      "gender": "male",
      "company": "GEEKOSIS",
      "email": "whitebrady@geekosis.com",
    },
    {
      "id": "5b2eee0a5a8611b0df09641e",
      "age": 26,
      "name": "Dillard Mitchell",
      "gender": "male",
      "company": "ENTHAZE",
      "email": "dillardmitchell@enthaze.com",
    },
    {
      "id": "5b2eee0a1bba93832b919d91",
      "age": 35,
      "name": "Jensen Le",
      "gender": "male",
      "company": "VIAGRAND",
      "email": "jensenle@viagrand.com",
    },
    {
      "id": "5b2eee0ad9ada83d0bce5772",
      "age": 30,
      "name": "Vilma Mayo",
      "gender": "female",
      "company": "XYQAG",
      "email": "vilmamayo@xyqag.com",
    },
    {
      "id": "5b2eee0a40e62cdfad1edf3b",
      "age": 20,
      "name": "Jones Oneal",
      "gender": "male",
      "company": "APEXTRI",
      "email": "jonesoneal@apextri.com",
    },
    {
      "id": "5b2eee0a41226617a23b227d",
      "age": 35,
      "name": "Fernandez Hopkins",
      "gender": "male",
      "company": "VIDTO",
      "email": "fernandezhopkins@vidto.com",
    },
    {
      "id": "5b2eee0a16b81de8c047c0b7",
      "age": 26,
      "name": "Ruby Carey",
      "gender": "female",
      "company": "VALPREAL",
      "email": "rubycarey@valpreal.com",
    },
    {
      "id": "5b2eee0a75f51e7458e600eb",
      "age": 34,
      "name": "Misty Oneil",
      "gender": "female",
      "company": "ZOARERE",
      "email": "mistyoneil@zoarere.com",
    },
    {
      "id": "5b2eee0a0d4975216430d0eb",
      "age": 38,
      "name": "Milagros Barrett",
      "gender": "female",
      "company": "KEGULAR",
      "email": "milagrosbarrett@kegular.com",
    },
    {
      "id": "5b2eee0a4ff5cc0e6fa1025f",
      "age": 32,
      "name": "Blake Webb",
      "gender": "male",
      "company": "DANCITY",
      "email": "blakewebb@dancity.com",
    },
    {
      "id": "5b2eee0a0d47c2b4cad8ea40",
      "age": 38,
      "name": "Sanders Jenkins",
      "gender": "male",
      "company": "ORBALIX",
      "email": "sandersjenkins@orbalix.com",
    },
    {
      "id": "5b2eee0aaec564b6a89dad20",
      "age": 30,
      "name": "Chase Graves",
      "gender": "male",
      "company": "VIRXO",
      "email": "chasegraves@virxo.com",
    },
    {
      "id": "5b2eee0a7d124ff77f4fccec",
      "age": 38,
      "name": "Dolores Payne",
      "gender": "female",
      "company": "ZOLAREX",
      "email": "dolorespayne@zolarex.com",
    },
    {
      "id": "5b2eee0a5c7a2719289cc164",
      "age": 28,
      "name": "Ericka Brown",
      "gender": "female",
      "company": "SQUISH",
      "email": "erickabrown@squish.com",
    },
    {
      "id": "5b2eee0a5e14851c66b7ac66",
      "age": 33,
      "name": "Myers Garner",
      "gender": "male",
      "company": "KNOWLYSIS",
      "email": "myersgarner@knowlysis.com",
    },
    {
      "id": "5b2eee0af13b74e60154c4fe",
      "age": 37,
      "name": "Terra Sandoval",
      "gender": "female",
      "company": "MITROC",
      "email": "terrasandoval@mitroc.com",
    },
    {
      "id": "5b2eee0ac33b966ec08308af",
      "age": 31,
      "name": "Strong Ramos",
      "gender": "male",
      "company": "ZENCO",
      "email": "strongramos@zenco.com",
    },
    {
      "id": "5b2eee0a8d1bb5e3fe1e185e",
      "age": 38,
      "name": "Cherry Ruiz",
      "gender": "female",
      "company": "CYTREK",
      "email": "cherryruiz@cytrek.com",
    },
    {
      "id": "5b2eee0ae2a672e9adf10872",
      "age": 28,
      "name": "Jennings Hammond",
      "gender": "male",
      "company": "QUORDATE",
      "email": "jenningshammond@quordate.com",
    },
    {
      "id": "5b2eee0a796d93fdd4154c2d",
      "age": 23,
      "name": "Andrews Sanford",
      "gender": "male",
      "company": "ISOSURE",
      "email": "andrewssanford@isosure.com",
    },
    {
      "id": "5b2eee0a4d717ec79e3ecbbf",
      "age": 31,
      "name": "Jordan Hines",
      "gender": "male",
      "company": "HYDROCOM",
      "email": "jordanhines@hydrocom.com",
    },
    {
      "id": "5b2eee0add8f6138c89935ea",
      "age": 23,
      "name": "Maura Bennett",
      "gender": "female",
      "company": "ZEDALIS",
      "email": "maurabennett@zedalis.com",
    },
    {
      "id": "5b2eee0adced0c823b16e0df",
      "age": 35,
      "name": "Glass Salas",
      "gender": "male",
      "company": "ZAYA",
      "email": "glasssalas@zaya.com",
    },
    {
      "id": "5b2eee0ab7d0d520668b5b3b",
      "age": 33,
      "name": "Perez Maddox",
      "gender": "male",
      "company": "BULLZONE",
      "email": "perezmaddox@bullzone.com",
    },
    {
      "id": "5b2eee0a8b772b10a071a3a5",
      "age": 21,
      "name": "Mendoza Burks",
      "gender": "male",
      "company": "KNEEDLES",
      "email": "mendozaburks@kneedles.com",
    },
    {
      "id": "5b2eee0a655163b38a1c8de8",
      "age": 22,
      "name": "Loraine Gonzales",
      "gender": "female",
      "company": "EVENTIX",
      "email": "lorainegonzales@eventix.com",
    },
    {
      "id": "5b2eee0a06463e8a045d33de",
      "age": 21,
      "name": "Rae West",
      "gender": "female",
      "company": "ISOSPHERE",
      "email": "raewest@isosphere.com",
    },
    {
      "id": "5b2eee0a775a40828277fef9",
      "age": 22,
      "name": "Amanda Colon",
      "gender": "female",
      "company": "SPORTAN",
      "email": "amandacolon@sportan.com",
    },
    {
      "id": "5b2eee0a8b88cd593c76d606",
      "age": 39,
      "name": "Foreman English",
      "gender": "male",
      "company": "IDEALIS",
      "email": "foremanenglish@idealis.com",
    },
    {
      "id": "5b2eee0a7f743a27f1ef2c5f",
      "age": 34,
      "name": "Snider Calhoun",
      "gender": "male",
      "company": "CYCLONICA",
      "email": "snidercalhoun@cyclonica.com",
    },
    {
      "id": "5b2eee0aff82751968c57e38",
      "age": 22,
      "name": "Suarez Mcgee",
      "gender": "male",
      "company": "FROLIX",
      "email": "suarezmcgee@frolix.com",
    },
    {
      "id": "5b2eee0afcb900a842aa1f04",
      "age": 39,
      "name": "Emma Sargent",
      "gender": "female",
      "company": "ASSITIA",
      "email": "emmasargent@assitia.com",
    },
    {
      "id": "5b2eee0a75c9d624b2abb7c3",
      "age": 21,
      "name": "Hutchinson Terry",
      "gender": "male",
      "company": "TOYLETRY",
      "email": "hutchinsonterry@toyletry.com",
    },
    {
      "id": "5b2eee0a7d26681317c7f95a",
      "age": 28,
      "name": "Hilda Howard",
      "gender": "female",
      "company": "MAXIMIND",
      "email": "hildahoward@maximind.com",
    },
    {
      "id": "5b2eee0a259afa5bdb2c9c4d",
      "age": 32,
      "name": "Haynes Hyde",
      "gender": "male",
      "company": "ENDIPINE",
      "email": "hayneshyde@endipine.com",
    },
    {
      "id": "5b2eee0a91f8c3322172a62a",
      "age": 35,
      "name": "Elvia Travis",
      "gender": "female",
      "company": "COMSTAR",
      "email": "elviatravis@comstar.com",
    },
    {
      "id": "5b2eee0a78694b3b0386fa05",
      "age": 30,
      "name": "Hurley Stone",
      "gender": "male",
      "company": "VETRON",
      "email": "hurleystone@vetron.com",
    },
    {
      "id": "5b2eee0ae230f59d90abd0d3",
      "age": 33,
      "name": "Louella Neal",
      "gender": "female",
      "company": "REVERSUS",
      "email": "louellaneal@reversus.com",
    },
    {
      "id": "5b2eee0aa37f0cf936e43747",
      "age": 30,
      "name": "Frye Fuller",
      "gender": "male",
      "company": "PLASMOX",
      "email": "fryefuller@plasmox.com",
    },
    {
      "id": "5b2eee0aa016450faf85adaa",
      "age": 27,
      "name": "Wiley Pruitt",
      "gender": "male",
      "company": "DADABASE",
      "email": "wileypruitt@dadabase.com",
    },
    {
      "id": "5b2eee0ad745528ba59585ef",
      "age": 30,
      "name": "Davidson Chandler",
      "gender": "male",
      "company": "ZIORE",
      "email": "davidsonchandler@ziore.com",
    },
    {
      "id": "5b2eee0a7d7fb10e311f1217",
      "age": 37,
      "name": "Shirley Higgins",
      "gender": "female",
      "company": "PLEXIA",
      "email": "shirleyhiggins@plexia.com",
    },
    {
      "id": "5b2eee0a82b0eadbdd379bd5",
      "age": 31,
      "name": "Noelle Delaney",
      "gender": "female",
      "company": "FREAKIN",
      "email": "noelledelaney@freakin.com",
    },
    {
      "id": "5b2eee0a37084f0cc733f162",
      "age": 27,
      "name": "Carmela Hess",
      "gender": "female",
      "company": "ACIUM",
      "email": "carmelahess@acium.com",
    },
    {
      "id": "5b2eee0a19ba882e2c2d690d",
      "age": 28,
      "name": "Parrish Alvarez",
      "gender": "male",
      "company": "ZYPLE",
      "email": "parrishalvarez@zyple.com",
    },
    {
      "id": "5b2eee0a054150df47a74e86",
      "age": 25,
      "name": "Nellie Espinoza",
      "gender": "female",
      "company": "ENERSOL",
      "email": "nellieespinoza@enersol.com",
    },
    {
      "id": "5b2eee0aa67fc0c2d9220fd7",
      "age": 25,
      "name": "Hobbs Snyder",
      "gender": "male",
      "company": "SOFTMICRO",
      "email": "hobbssnyder@softmicro.com",
    },
    {
      "id": "5b2eee0adb7cfed4af783c8d",
      "age": 34,
      "name": "Beulah Cross",
      "gender": "female",
      "company": "ZANILLA",
      "email": "beulahcross@zanilla.com",
    },
    {
      "id": "5b2eee0ab542a8aab32d5688",
      "age": 32,
      "name": "Olive Mejia",
      "gender": "female",
      "company": "KENEGY",
      "email": "olivemejia@kenegy.com",
    },
    {
      "id": "5b2eee0a6f8c2897199b4206",
      "age": 39,
      "name": "Michelle Thompson",
      "gender": "female",
      "company": "IRACK",
      "email": "michellethompson@irack.com",
    },
    {
      "id": "5b2eee0aac69d7b8b62d8175",
      "age": 34,
      "name": "Savannah Sellers",
      "gender": "female",
      "company": "ZILPHUR",
      "email": "savannahsellers@zilphur.com",
    },
    {
      "id": "5b2eee0aa8deb160aae22b80",
      "age": 24,
      "name": "Arlene Woods",
      "gender": "female",
      "company": "CONCILITY",
      "email": "arlenewoods@concility.com",
    },
    {
      "id": "5b2eee0a1c7d1f9a917ddfe4",
      "age": 31,
      "name": "Madeleine Lewis",
      "gender": "female",
      "company": "ATGEN",
      "email": "madeleinelewis@atgen.com",
    },
    {
      "id": "5b2eee0a687b0c8c08798cad",
      "age": 40,
      "name": "Tamika Sexton",
      "gender": "female",
      "company": "VICON",
      "email": "tamikasexton@vicon.com",
    },
    {
      "id": "5b2eee0a8ca201ad091f7d61",
      "age": 35,
      "name": "Ila Watson",
      "gender": "female",
      "company": "ORONOKO",
      "email": "ilawatson@oronoko.com",
    },
    {
      "id": "5b2eee0a4b8671583018d66f",
      "age": 29,
      "name": "Lula Tyson",
      "gender": "female",
      "company": "KOZGENE",
      "email": "lulatyson@kozgene.com",
    },
    {
      "id": "5b2eee0a781428aa3982edce",
      "age": 22,
      "name": "Madeline Barron",
      "gender": "female",
      "company": "OCEANICA",
      "email": "madelinebarron@oceanica.com",
    },
    {
      "id": "5b2eee0afb27e3ae039f7344",
      "age": 30,
      "name": "Ruthie Carpenter",
      "gender": "female",
      "company": "SENSATE",
      "email": "ruthiecarpenter@sensate.com",
    },
    {
      "id": "5b2eee0ab1fd9df0d190150a",
      "age": 20,
      "name": "Hallie Peterson",
      "gender": "female",
      "company": "VINCH",
      "email": "halliepeterson@vinch.com",
    },
    {
      "id": "5b2eee0a02c38b660a6c94f7",
      "age": 23,
      "name": "Chambers Padilla",
      "gender": "male",
      "company": "QUAILCOM",
      "email": "chamberspadilla@quailcom.com",
    },
    {
      "id": "5b2eee0af79960b887c00c3f",
      "age": 31,
      "name": "Shawna Mathis",
      "gender": "female",
      "company": "KANGLE",
      "email": "shawnamathis@kangle.com",
    }
  ]

  getContacts(): Observable<Contact[]> {
    return of(this.contacts).pipe(
      delay(500),
      map(contacts => contacts.sort((a, b) => a.age - b.age))
    );
  } 
}
